# docker compose -f .\docker-postgres.yml up -d --force-recreate

version: '3.5'

volumes:
  data:

services:
  database:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: galva
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
    volumes:
      - data:/var/lib/postgresql/data